create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  source_page text,
  page_url text,
  language text,
  user_agent text,
  status text not null default 'new',
  submitted_at timestamptz not null default now()
);

create table if not exists public.join_applications (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone_contact text not null,
  course text not null,
  study_year text not null,
  motivation text not null,
  linkedin text,
  age integer,
  source_page text,
  page_url text,
  language text,
  user_agent text,
  status text not null default 'new',
  submitted_at timestamptz not null default now(),
  constraint join_applications_age_check check (age is null or age between 16 and 99)
);

alter table public.join_applications
  add column if not exists phone_contact text;

create index if not exists contact_submissions_submitted_at_idx
  on public.contact_submissions (submitted_at desc);

create index if not exists contact_submissions_status_idx
  on public.contact_submissions (status);

create index if not exists join_applications_submitted_at_idx
  on public.join_applications (submitted_at desc);

create index if not exists join_applications_status_idx
  on public.join_applications (status);

alter table public.contact_submissions enable row level security;
alter table public.join_applications enable row level security;

revoke all on public.contact_submissions from anon, authenticated;
revoke all on public.join_applications from anon, authenticated;

grant insert on public.contact_submissions to anon, authenticated;
grant insert on public.join_applications to anon, authenticated;

grant usage, select on sequence public.contact_submissions_id_seq to anon, authenticated;
grant usage, select on sequence public.join_applications_id_seq to anon, authenticated;

drop policy if exists "Allow public inserts on contact_submissions" on public.contact_submissions;
create policy "Allow public inserts on contact_submissions"
  on public.contact_submissions
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Allow public inserts on join_applications" on public.join_applications;
create policy "Allow public inserts on join_applications"
  on public.join_applications
  for insert
  to anon, authenticated
  with check (true);

create extension if not exists pgcrypto;

create table if not exists public.user_profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  role text not null default 'member',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_profiles_role_check check (role in ('admin', 'member', 'communication_team', 'hr_team'))
);

create table if not exists public.team_members (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users (id) on delete set null,
  name text not null,
  role text not null,
  description text,
  photo_url text,
  linkedin_url text,
  email text,
  joined_month integer,
  joined_year integer,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint team_members_joined_month_check check (joined_month is null or joined_month between 1 and 12),
  constraint team_members_joined_year_check check (joined_year is null or joined_year between 2000 and 2100)
);

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  slug text,
  title text not null,
  description text,
  image_url text,
  image_urls jsonb not null default '[]'::jsonb,
  project_date date,
  category text,
  tags text[] not null default '{}',
  external_link text,
  status text not null default 'draft',
  details jsonb not null default '{}'::jsonb,
  sort_order integer not null default 1000,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  constraint projects_status_check check (status in ('draft', 'in_review', 'published', 'archived'))
);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  action text not null,
  entity_type text,
  entity_label text,
  user_id uuid references auth.users (id) on delete set null,
  user_label text,
  created_at timestamptz not null default now()
);

create table if not exists public.project_members (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  team_member_id uuid not null references public.team_members (id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint project_members_unique unique (project_id, team_member_id)
);

create table if not exists public.interview_evaluations (
  id uuid primary key default gen_random_uuid(),
  candidate_name text not null,
  interview_date date,
  course_year text,
  interviewers text,
  potential_area text,
  final_decision text not null default 'advance',
  scores jsonb not null default '{}'::jsonb,
  final_reading jsonb not null default '{}'::jsonb,
  strongest_point text,
  main_risk text,
  doubts_to_validate text,
  evaluator_comment text,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint interview_evaluations_final_decision_check check (final_decision in ('advance', 'reject'))
);

alter table public.user_profiles
  add column if not exists email text,
  add column if not exists role text not null default 'member',
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.user_profiles
  drop constraint if exists user_profiles_role_check;

alter table public.user_profiles
  add constraint user_profiles_role_check
  check (role in ('admin', 'member', 'communication_team', 'hr_team'));

alter table public.team_members
  add column if not exists user_id uuid references auth.users (id) on delete set null,
  add column if not exists name text,
  add column if not exists role text,
  add column if not exists description text,
  add column if not exists photo_url text,
  add column if not exists linkedin_url text,
  add column if not exists email text,
  add column if not exists joined_month integer,
  add column if not exists joined_year integer,
  add column if not exists is_active boolean not null default true,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.projects
  add column if not exists slug text,
  add column if not exists title text,
  add column if not exists description text,
  add column if not exists image_url text,
  add column if not exists image_urls jsonb not null default '[]'::jsonb,
  add column if not exists project_date date,
  add column if not exists category text,
  add column if not exists tags text[] not null default '{}',
  add column if not exists external_link text,
  add column if not exists status text not null default 'draft',
  add column if not exists archived_at timestamptz,
  add column if not exists details jsonb not null default '{}'::jsonb,
  add column if not exists sort_order integer not null default 1000,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.interview_evaluations
  add column if not exists candidate_name text,
  add column if not exists interview_date date,
  add column if not exists course_year text,
  add column if not exists interviewers text,
  add column if not exists potential_area text,
  add column if not exists final_decision text not null default 'advance',
  add column if not exists scores jsonb not null default '{}'::jsonb,
  add column if not exists final_reading jsonb not null default '{}'::jsonb,
  add column if not exists strongest_point text,
  add column if not exists main_risk text,
  add column if not exists doubts_to_validate text,
  add column if not exists evaluator_comment text,
  add column if not exists created_by uuid references auth.users (id) on delete set null,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists user_profiles_email_idx
  on public.user_profiles (lower(email))
  where email is not null;

create unique index if not exists projects_slug_idx
  on public.projects (slug);

alter table public.projects
  drop constraint if exists projects_status_check;

alter table public.projects
  add constraint projects_status_check
  check (status in ('draft', 'in_review', 'published', 'archived'));

create index if not exists team_members_user_id_idx
  on public.team_members (user_id);

do $$
begin
  if not exists (
    select 1
    from public.team_members
    where user_id is not null
    group by user_id
    having count(*) > 1
  ) then
    create unique index if not exists team_members_user_id_unique_idx
      on public.team_members (user_id)
      where user_id is not null;
  end if;
end;
$$;

create index if not exists team_members_is_active_idx
  on public.team_members (is_active);

create index if not exists projects_status_idx
  on public.projects (status);

create index if not exists projects_project_date_idx
  on public.projects (project_date desc);

create index if not exists project_members_project_id_idx
  on public.project_members (project_id);

create index if not exists project_members_team_member_id_idx
  on public.project_members (team_member_id);

create index if not exists interview_evaluations_interview_date_idx
  on public.interview_evaluations (interview_date desc);

create index if not exists interview_evaluations_created_at_idx
  on public.interview_evaluations (created_at desc);

create index if not exists interview_evaluations_created_by_idx
  on public.interview_evaluations (created_by);

create index if not exists interview_evaluations_candidate_name_idx
  on public.interview_evaluations (lower(candidate_name));

create index if not exists audit_logs_created_at_idx
  on public.audit_logs (created_at desc);

create index if not exists audit_logs_user_id_idx
  on public.audit_logs (user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_user_profiles_updated_at on public.user_profiles;
create trigger set_user_profiles_updated_at
  before update on public.user_profiles
  for each row
  execute function public.set_updated_at();

drop trigger if exists set_team_members_updated_at on public.team_members;
create trigger set_team_members_updated_at
  before update on public.team_members
  for each row
  execute function public.set_updated_at();

drop trigger if exists set_projects_updated_at on public.projects;
create trigger set_projects_updated_at
  before update on public.projects
  for each row
  execute function public.set_updated_at();

drop trigger if exists set_interview_evaluations_updated_at on public.interview_evaluations;
create trigger set_interview_evaluations_updated_at
  before update on public.interview_evaluations
  for each row
  execute function public.set_updated_at();

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select role from public.user_profiles where id = auth.uid()),
    'member'
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_user_role() = 'admin';
$$;

create or replace function public.can_manage_projects()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_user_role() in ('admin', 'communication_team');
$$;

create or replace function public.can_manage_hr()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_user_role() in ('admin', 'hr_team');
$$;

create or replace function public.prevent_member_restricted_team_updates()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.is_admin() then
    return new;
  end if;

  if new.user_id is distinct from old.user_id
    or new.is_active is distinct from old.is_active then
    raise exception 'Members cannot change restricted team profile fields';
  end if;

  return new;
end;
$$;

drop trigger if exists prevent_member_restricted_team_updates on public.team_members;
create trigger prevent_member_restricted_team_updates
  before update on public.team_members
  for each row
  execute function public.prevent_member_restricted_team_updates();

create or replace function public.sync_auth_user_backoffice_profile(
  target_user_id uuid,
  target_email text,
  target_meta jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  display_name text := coalesce(
    nullif(coalesce(target_meta, '{}'::jsonb)->>'name', ''),
    nullif(coalesce(target_meta, '{}'::jsonb)->>'full_name', ''),
    nullif(coalesce(target_meta, '{}'::jsonb)->>'display_name', ''),
    nullif(split_part(coalesce(target_email, ''), '@', 1), ''),
    'Novo membro'
  );
  default_team_role text := 'Membro da equipa';
begin
  insert into public.user_profiles (id, email, role)
  values (target_user_id, target_email, 'member')
  on conflict (id) do nothing;

  update public.team_members tm
  set
    user_id = target_user_id,
    name = coalesce(nullif(tm.name, ''), display_name),
    role = coalesce(nullif(tm.role, ''), default_team_role),
    email = coalesce(nullif(tm.email, ''), target_email)
  where tm.ctid = (
    select candidate.ctid
    from public.team_members candidate
    where candidate.user_id is null
      and target_email is not null
      and candidate.email is not null
      and lower(candidate.email) = lower(target_email)
    order by candidate.updated_at desc nulls last, candidate.created_at desc nulls last
    limit 1
  )
    and not exists (
      select 1
      from public.team_members existing
      where existing.user_id = target_user_id
    );

  insert into public.team_members (user_id, name, role, email, is_active)
  select target_user_id, display_name, default_team_role, target_email, true
  where not exists (
    select 1
    from public.team_members existing
    where existing.user_id = target_user_id
  );
end;
$$;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.sync_auth_user_backoffice_profile(new.id, new.email, new.raw_user_meta_data);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_create_profile on auth.users;
create trigger on_auth_user_created_create_profile
  after insert on auth.users
  for each row
  execute function public.handle_new_auth_user();

select public.sync_auth_user_backoffice_profile(auth_user.id, auth_user.email, auth_user.raw_user_meta_data)
from auth.users as auth_user;

alter table public.user_profiles enable row level security;
alter table public.team_members enable row level security;
alter table public.projects enable row level security;
alter table public.project_members enable row level security;
alter table public.interview_evaluations enable row level security;
alter table public.audit_logs enable row level security;

revoke all on public.user_profiles from anon, authenticated;
revoke all on public.team_members from anon, authenticated;
revoke all on public.projects from anon, authenticated;
revoke all on public.project_members from anon, authenticated;
revoke all on public.interview_evaluations from anon, authenticated;
revoke all on public.audit_logs from anon, authenticated;

grant select on public.team_members to anon, authenticated;
grant select on public.projects to anon, authenticated;
grant select on public.project_members to anon, authenticated;

grant select, insert, update, delete on public.user_profiles to authenticated;
grant update, delete on public.team_members to authenticated;
grant insert, update, delete on public.projects to authenticated;
grant insert, update, delete on public.project_members to authenticated;
grant select, insert, update, delete on public.interview_evaluations to authenticated;
grant select, insert on public.audit_logs to authenticated;

drop policy if exists "Users can read own profile or admins read all" on public.user_profiles;
create policy "Users can read own profile or admins read all"
  on public.user_profiles
  for select
  to authenticated
  using (id = auth.uid() or public.is_admin());

drop policy if exists "Admins manage user profiles" on public.user_profiles;
create policy "Admins manage user profiles"
  on public.user_profiles
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Public can read active team members" on public.team_members;
create policy "Public can read active team members"
  on public.team_members
  for select
  to anon, authenticated
  using (is_active = true or public.is_admin() or public.can_manage_projects() or user_id = auth.uid());

drop policy if exists "Admins can insert team members" on public.team_members;

drop policy if exists "Admins can update all team members and members update own" on public.team_members;
create policy "Admins can update all team members and members update own"
  on public.team_members
  for update
  to authenticated
  using (public.is_admin() or user_id = auth.uid())
  with check (public.is_admin() or user_id = auth.uid());

drop policy if exists "Admins can delete team members" on public.team_members;
create policy "Admins can delete team members"
  on public.team_members
  for delete
  to authenticated
  using (public.is_admin());

drop policy if exists "Public can read published projects" on public.projects;
create policy "Public can read published projects"
  on public.projects
  for select
  to anon, authenticated
  using (status = 'published' or public.can_manage_projects());

drop policy if exists "Admins can insert projects" on public.projects;
create policy "Admins can insert projects"
  on public.projects
  for insert
  to authenticated
  with check (public.can_manage_projects());

drop policy if exists "Admins can update projects" on public.projects;
create policy "Admins can update projects"
  on public.projects
  for update
  to authenticated
  using (public.can_manage_projects())
  with check (public.can_manage_projects());

drop policy if exists "Admins can delete projects" on public.projects;
create policy "Admins can delete projects"
  on public.projects
  for delete
  to authenticated
  using (public.is_admin());

drop policy if exists "Public can read published project members" on public.project_members;
create policy "Public can read published project members"
  on public.project_members
  for select
  to anon, authenticated
  using (
    public.can_manage_projects()
    or exists (
      select 1
      from public.projects p
      where p.id = project_members.project_id
        and p.status = 'published'
    )
  );

drop policy if exists "Admins can manage project members" on public.project_members;
create policy "Admins can manage project members"
  on public.project_members
  for all
  to authenticated
  using (public.can_manage_projects())
  with check (public.can_manage_projects());

drop policy if exists "Admins can manage interview evaluations" on public.interview_evaluations;
create policy "Admins can manage interview evaluations"
  on public.interview_evaluations
  for all
  to authenticated
  using (public.can_manage_hr())
  with check (public.can_manage_hr());

drop policy if exists "Admins can read audit logs" on public.audit_logs;
create policy "Admins can read audit logs"
  on public.audit_logs
  for select
  to authenticated
  using (public.is_admin());

drop policy if exists "Authenticated users can insert audit logs" on public.audit_logs;
create policy "Authenticated users can insert audit logs"
  on public.audit_logs
  for insert
  to authenticated
  with check (auth.uid() = user_id or user_id is null);

insert into storage.buckets (id, name, public)
values
  ('team-photos', 'team-photos', true),
  ('project-images', 'project-images', true)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "Public can read Rise Up storage" on storage.objects;
create policy "Public can read Rise Up storage"
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id in ('team-photos', 'project-images'));

drop policy if exists "Authenticated users can upload team photos" on storage.objects;
create policy "Authenticated users can upload team photos"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'team-photos'
    and (
      public.is_admin()
      or (storage.foldername(name))[2] = auth.uid()::text
    )
  );

drop policy if exists "Authenticated users can update team photos" on storage.objects;
create policy "Authenticated users can update team photos"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'team-photos'
    and (
      public.is_admin()
      or (storage.foldername(name))[2] = auth.uid()::text
    )
  )
  with check (
    bucket_id = 'team-photos'
    and (
      public.is_admin()
      or (storage.foldername(name))[2] = auth.uid()::text
    )
  );

drop policy if exists "Admins can manage project images" on storage.objects;
create policy "Admins can manage project images"
  on storage.objects
  for all
  to authenticated
  using (bucket_id = 'project-images' and public.can_manage_projects())
  with check (bucket_id = 'project-images' and public.can_manage_projects());

with seed_projects (
  slug,
  title,
  description,
  image_url,
  image_urls,
  project_date,
  category,
  tags,
  status,
  sort_order,
  details
) as (
  values
  (
    'deeplearn25',
    'DeepLearn25',
    'Participacao na coordenacao logistica e producao de media numa das principais conferencias academicas de IA na Europa.',
    'img/Projetos/DeepLearn%202025/deeplearn%202025.jpg',
    '["img/Projetos/DeepLearn%202025/deeplearn%202025.jpg", "img/Projetos/DeepLearn%202025/equipa.jpg"]'::jsonb,
    '2025-07-01',
    'Conferencia Internacional',
    array['media', 'logistica', 'inteligencia artificial'],
    'published',
    10,
    '{"meta": "Data: julho de 2025 | Funcao: equipa de comunicacao", "points": ["Apoio na acreditacao de participantes e gestao de sessoes.", "Captacao e edicao de conteudo audiovisual de palestras, networking e hackathon.", "Documentacao e divulgacao dos principais momentos do evento.", "Producao de videos usados numa peca televisiva do Porto Canal sobre o DeepLearn."]}'::jsonb
  ),
  (
    'hoje-2025',
    'HOJE - National Exhibition of Young Entrepreneurs 2025',
    'Participacao na organizacao e gestao do HOJE 2025, integrado na Mostra Nacional Jovens Empreendedores da Fundacao da Juventude.',
    'img/Projetos/HOJE%20%E2%80%93%20%202025/logotipo.jpg',
    '["img/Projetos/HOJE%20%E2%80%93%20%202025/logotipo.jpg"]'::jsonb,
    '2025-06-03',
    'Hackathon',
    array['hackathon', 'empreendedorismo', 'organizacao'],
    'published',
    20,
    '{"meta": "Data: 3 e 4 de junho de 2025 | Local: Alfandega do Porto", "points": ["Planeamento e logistica do hackathon.", "Gestao de comunicacao, incluindo convite a mentores e speakers.", "Acompanhamento e apoio continuo as equipas participantes.", "Coordenacao dos pitches finais e entrega de materiais."], "result": "Destaque: apresentacao do projeto Move Verde, vencedor de dois premios."}'::jsonb
  ),
  (
    'protocolo-aiesec',
    'Protocolo com a AIESEC',
    'Estabelecimento de parceria com a AIESEC para promover desenvolvimento pessoal, lideranca jovem, networking e oportunidades internacionais. Coorganizacao do evento Transforma o teu futuro, realizado a 29 de abril de 2025 .',
    'img/Projetos/Aiesec/momento.jpg',
    '["img/Projetos/Aiesec/momento.jpg"]'::jsonb,
    '2025-03-01',
    'Parceria Estrategica',
    array['parceria', 'aiesec', 'lideranca'],
    'published',
    30,
    '{"meta": "Periodo: marco de 2025 - atualidade"}'::jsonb
  ),
  (
    'qual-o-valor-das-coisas',
    'Qual o valor das coisas? - Financial Literacy Workshops',
    'Desenvolvimento e dinamizacao de workshops de literacia financeira para estudantes universitarios, com conteudos praticos e abordagem pedagogica interativa.',
    'img/Projetos/Workshop%20literacia%20financeira/momento.jpg',
    '["img/Projetos/Workshop%20literacia%20financeira/momento.jpg"]'::jsonb,
    '2024-09-01',
    'Formacao',
    array['literacia financeira', 'workshops', 'formacao'],
    'published',
    40,
    '{"meta": "Periodo: setembro de 2024 a janeiro de 2025", "points": ["Criacao de conteudos sobre orcamento, poupanca, investimento e impostos.", "Lideranca da equipa na preparacao de atividades e planeamento logistico.", "Adaptacao de temas complexos para formatos claros e aplicaveis.", "Promocao de um ambiente colaborativo e participativo entre estudantes."]}'::jsonb
  ),
  (
    'challanje-2024',
    'Organizacao do evento ChallANJE 2024',
    'Planeamento e execucao do evento em colaboracao entre Rise Up e ANJE, com foco em coordenacao operacional, captacao de conteudos multimedia e comunicacao digital em tempo real.',
    'img/Projetos/ChallANJE%202024/evento.jpg',
    '["img/Projetos/ChallANJE%202024/evento.jpg", "img/Projetos/ChallANJE%202024/trabalho.jpg", "img/Projetos/ChallANJE%202024/momento%20organiza%C3%A7%C3%A3o%20almo%C3%A7o.jpg", "img/Projetos/ChallANJE%202024/certificado%20Riseup.jpg"]'::jsonb,
    '2024-09-01',
    'Organizacao',
    array['anje', 'organizacao', 'evento'],
    'published',
    50,
    '{"meta": "Periodo: setembro de 2024 a novembro de 2024 | Local: Terminal de Cruzeiros de Leixoes", "brands": "Empresas em destaque: Porsche, Super Bock Group, Pedacos de Cacau, RFM e Bosch."}'::jsonb
  ),
  (
    'hoje-2024',
    'HOJE - HackathON Jovens Empreendedores 2024',
    'Primeira edicao da iniciativa da Fundacao da Juventude, integrada na Mostra Nacional Jovens Empreendedores 2024.',
    'img/Projetos/HOJE%20%E2%80%93%202024/logotipo.jpg',
    '["img/Projetos/HOJE%20%E2%80%93%202024/logotipo.jpg", "img/Projetos/HOJE%20%E2%80%93%202024/momento.jpg", "img/Projetos/HOJE%20%E2%80%93%202024/momento%202.jpg", "img/Projetos/HOJE%20%E2%80%93%202024/estudantes.jpg", "img/Projetos/HOJE%20%E2%80%93%202024/estudantes%202.jpg", "img/Projetos/HOJE%20%E2%80%93%202024/grupo%20Riseup.jpg"]'::jsonb,
    '2024-05-27',
    'Evento',
    array['hackathon', 'empreendedorismo', 'fundacao da juventude'],
    'published',
    60,
    '{"meta": "Data: 27 de maio de 2024 (9h00-20h00) | Local: Centro de Congressos da Alfandega do Porto", "points": ["Ligacao entre jovens talentos e marcas de referencia em Portugal.", "Geracao de novas perspetivas e ideias aplicaveis a desafios reais.", "Desenvolvimento de solucoes viaveis em contexto de trabalho intensivo.", "Reforco da visibilidade de marcas e valorizacao do talento jovem."], "brands": "Marcas participantes: Fruut, Super Bock, Ambar, Capgemini e Artnetic.", "result": "Escala: aproximadamente 100 participantes."}'::jsonb
  ),
  (
    'tedx-figueiro-dos-vinhos',
    'TEDx Figueiro dos Vinhos',
    'Responsabilidade pela cobertura audiovisual e pos-producao do evento, com foco na qualidade editorial e cumprimento dos padroes TEDx.',
    'img/Projetos/TEDx%20Figueir%C3%B3%20dos%20vinhos/Palestra.jpg',
    '["img/Projetos/TEDx%20Figueir%C3%B3%20dos%20vinhos/Palestra.jpg", "img/Projetos/TEDx%20Figueir%C3%B3%20dos%20vinhos/momento%20trabalho.jpg", "img/Projetos/TEDx%20Figueir%C3%B3%20dos%20vinhos/equipa.jpg", "img/Projetos/TEDx%20Figueir%C3%B3%20dos%20vinhos/Membro%20com%20Tim%20Vieira.jpg"]'::jsonb,
    '2024-05-01',
    'Media Production',
    array['tedx', 'media', 'producao audiovisual'],
    'published',
    70,
    '{"meta": "Data: maio de 2024", "points": ["Captacao de video dos talks, bastidores e interacao do publico.", "Cobertura fotografica para comunicacao e arquivo.", "Criacao de conteudos curtos para redes sociais.", "Edicao das talks completas para publicacao no canal oficial TEDx YouTube."]}'::jsonb
  ),
  (
    'challanje-2023',
    'ChallANJE 2023',
    'Participacao na 4. edicao do ChallANJE, com desenvolvimento do plano de comunicacao do evento e gestao operacional com uma equipa de jovens voluntarios.',
    'img/Projetos/ChallANJE%202023/logotipo.jpg',
    '["img/Projetos/ChallANJE%202023/logotipo.jpg", "img/Projetos/ChallANJE%202023/equipa%20Riseup%20challange.jpg"]'::jsonb,
    null,
    'Maratona de Criatividade',
    array['challanje', 'comunicacao', 'voluntariado'],
    'published',
    80,
    '{"points": ["Participacao na 4. edicao, com 150 estudantes e 6 empresas.", "Desenvolvimento do plano de comunicacao do evento.", "Gestao operacional com uma equipa de 30 jovens voluntarios.", "Resolucao de desafios e imprevistos de ultima hora."]}'::jsonb
  )
)
insert into public.projects (
  slug,
  title,
  description,
  image_url,
  image_urls,
  project_date,
  category,
  tags,
  status,
  sort_order,
  details
)
select
  seed.slug::text,
  seed.title::text,
  seed.description::text,
  seed.image_url::text,
  seed.image_urls::jsonb,
  seed.project_date::date,
  seed.category::text,
  seed.tags::text[],
  seed.status::text,
  seed.sort_order::integer,
  seed.details::jsonb
from seed_projects seed
where not exists (
  select 1
  from public.projects existing
  where existing.slug = seed.slug
     or lower(existing.title) = lower(seed.title)
)
on conflict (slug) do nothing;
