create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  source_page text,
  page_url text,
  language text,
  user_agent text,
  status text not null default 'new',
  submitted_at timestamptz not null default now()
);

create table if not exists public.join_applications (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone_contact text not null,
  course text not null,
  study_year text not null,
  motivation text not null,
  linkedin text,
  age integer,
  source_page text,
  page_url text,
  language text,
  user_agent text,
  status text not null default 'new',
  submitted_at timestamptz not null default now(),
  constraint join_applications_age_check check (age is null or age between 16 and 99)
);

alter table public.join_applications
  add column if not exists phone_contact text;

create index if not exists contact_submissions_submitted_at_idx
  on public.contact_submissions (submitted_at desc);

create index if not exists contact_submissions_status_idx
  on public.contact_submissions (status);

create index if not exists join_applications_submitted_at_idx
  on public.join_applications (submitted_at desc);

create index if not exists join_applications_status_idx
  on public.join_applications (status);

alter table public.contact_submissions enable row level security;
alter table public.join_applications enable row level security;

revoke all on public.contact_submissions from anon, authenticated;
revoke all on public.join_applications from anon, authenticated;

grant insert on public.contact_submissions to anon, authenticated;
grant insert on public.join_applications to anon, authenticated;

grant usage, select on sequence public.contact_submissions_id_seq to anon, authenticated;
grant usage, select on sequence public.join_applications_id_seq to anon, authenticated;

drop policy if exists "Allow public inserts on contact_submissions" on public.contact_submissions;
create policy "Allow public inserts on contact_submissions"
  on public.contact_submissions
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Allow public inserts on join_applications" on public.join_applications;
create policy "Allow public inserts on join_applications"
  on public.join_applications
  for insert
  to anon, authenticated
  with check (true);
